"""empty message

Revision ID: 1a768edeaaa4
Revises: 6a7350c4030f
Create Date: 2023-02-13 01:26:38.795613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a768edeaaa4'
down_revision = '6a7350c4030f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'id', autoincrement=True)
    op.alter_column('Artist', 'id', autoincrement=True)
    op.alter_column('Show', 'id', autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'id', autoincrement=True)
    op.drop_column('Artist', 'id', autoincrement=True)
    op.drop_column('Show', 'id')

    # ### end Alembic commands ###